# -*- coding: utf-8 -*-
"""Catalogo dos 32 streamings (extraido sem alteracao)."""

STREAMINGS_DB = {
    "Netflix": {"url": "https://www.netflix.com", "category": "Filmes", "icon": "\U0001F3AC", "color": "#E50914",
                "deep_link": "netflix://watch/{id}", "url_template": "https://www.netflix.com/title/{id}",
                "top_content": [{"id": "81345507", "title": "Stranger Things"}, {"id": "80175798", "title": "The Witcher"}, {"id": "80234375", "title": "Dahmer"}]},
    "YouTube": {"url": "https://www.youtube.com", "category": "Videos", "icon": "\U0001F509", "color": "#FF0000",
                "deep_link": "youtube://watch?v={id}", "url_template": "https://www.youtube.com/watch?v={id}",
                "top_content": [{"id": "dQw4w9WgXcQ", "title": "Never Gonna Give You Up"}, {"id": "M7FIvfx5J10", "title": "Minecraft Trailer"}, {"id": "kJQP7kiw5Fk", "title": "Despacito"}]},
    "Spotify": {"url": "https://www.spotify.com", "category": "Musica", "icon": "\U0001F3B5", "color": "#1DB954",
                "deep_link": "", "url_template": "https://open.spotify.com",
                "top_content": [{"id": "", "title": "Top Hits"}, {"id": "", "title": "Discover Weekly"}, {"id": "", "title": "Release Radar"}]},
    "Disney+": {"url": "https://www.disneyplus.com", "category": "Filmes", "icon": "\U0001F3AD", "color": "#113CCF",
                "deep_link": "disneyplus://title/{id}", "url_template": "https://www.disneyplus.com/video/{id}",
                "top_content": [{"id": "4uTZvR2F8zEJ", "title": "The Mandalorian"}, {"id": "2XmJZ2k4nQ1P", "title": "Loki"}, {"id": "3yQJmXk9tR5W", "title": "Deadpool & Wolverine"}]},
    "Amazon Prime": {"url": "https://www.primevideo.com", "category": "Filmes", "icon": "\U0001F4E6", "color": "#00A8E1",
                     "deep_link": "primevideo://detail/{id}", "url_template": "https://www.primevideo.com/dp/{id}",
                     "top_content": [{"id": "tt17402904", "title": "The Boys"}, {"id": "tt17276090", "title": "Fallout"}, {"id": "tt15398776", "title": "Reacher"}]},
    "HBO Max": {"url": "https://www.max.com", "category": "Filmes", "icon": "\U0001F4FA", "color": "#B01CDE",
                "deep_link": "hbomax://title/{id}", "url_template": "https://www.max.com/title/{id}",
                "top_content": [{"id": "tt0903747", "title": "Breaking Bad"}, {"id": "tt28404886", "title": "The Last of Us"}, {"id": "tt33594241", "title": "House of the Dragon"}]},
    "Twitch": {"url": "https://www.twitch.tv", "category": "Videos", "icon": "\U0001F6A8", "color": "#9146FF",
               "deep_link": "twitch://stream/{id}", "url_template": "https://www.twitch.tv/{id}",
               "top_content": [{"id": "shroud", "title": "shroud"}, {"id": "xQc", "title": "xQc"}, {"id": "ironmouse", "title": "ironmouse"}]},
    "Crunchyroll": {"url": "https://www.crunchyroll.com", "category": "Filmes", "icon": "\U0001F310", "color": "#F47521",
                    "deep_link": "", "url_template": "https://www.crunchyroll.com/series/{id}",
                    "top_content": [{"id": "", "title": "One Piece"}, {"id": "", "title": "Jujutsu Kaisen"}, {"id": "", "title": "Demon Slayer"}]},
    "Dailymotion": {"url": "https://www.dailymotion.com", "category": "Videos", "icon": "\U0001F4F1", "color": "#0066DC",
                    "deep_link": "", "url_template": "https://www.dailymotion.com/video/{id}",
                    "top_content": [{"id": "", "title": "Trending"}, {"id": "", "title": "News"}, {"id": "", "title": "Sports"}]},
    "Bandcamp": {"url": "https://www.bandcamp.com", "category": "Musica", "icon": "\U0001F3BA", "color": "#629AA9",
                 "deep_link": "", "url_template": "https://bandcamp.com",
                 "top_content": [{"id": "", "title": "New Releases"}, {"id": "", "title": "Best Sellers"}, {"id": "", "title": "Staff Picks"}]},
    "SoundCloud": {"url": "https://www.soundcloud.com", "category": "Musica", "icon": "\U0001F3B6", "color": "#FF5500",
                   "deep_link": "", "url_template": "https://soundcloud.com/{id}",
                   "top_content": [{"id": "", "title": "Top 50"}, {"id": "", "title": "New & Hot"}, {"id": "", "title": "Chill"}]},
    "Pluto TV": {"url": "https://pluto.tv", "category": "Filmes", "icon": "\U0001F52A", "color": "#2B2B2B",
                 "deep_link": "", "url_template": "https://pluto.tv",
                 "top_content": [{"id": "", "title": "Live TV"}, {"id": "", "title": "Movies"}, {"id": "", "title": "Entertainment"}]},
    "Apple TV": {"url": "https://tv.apple.com", "category": "Filmes", "icon": "\U0001F3AC", "color": "#555555",
                 "deep_link": "tv://{id}", "url_template": "https://tv.apple.com/show/{id}",
                 "top_content": [{"id": "", "title": "Ted Lasso"}, {"id": "", "title": "Severance"}, {"id": "", "title": "The Morning Show"}]},
    "Peacock": {"url": "https://www.peacocktv.com", "category": "Filmes", "icon": "\U0001F985", "color": "#000000",
                "deep_link": "", "url_template": "https://www.peacocktv.com/{id}",
                "top_content": [{"id": "", "title": "The Office"}, {"id": "", "title": "Poker Face"}, {"id": "", "title": "Twisted Metal"}]},
    "Paramount+": {"url": "https://www.paramountplus.com", "category": "Filmes", "icon": "\u2B50", "color": "#0064FF",
                   "deep_link": "", "url_template": "https://www.paramountplus.com/{id}",
                   "top_content": [{"id": "", "title": "Star Trek"}, {"id": "", "title": "Yellowjackets"}, {"id": "", "title": "1883"}]},
    "Discovery+": {"url": "https://www.discoveryplus.com", "category": "Filmes", "icon": "\U0001F30D", "color": "#0A0A0A",
                   "deep_link": "", "url_template": "https://www.discoveryplus.com/{id}",
                   "top_content": [{"id": "", "title": "Planet Earth"}, {"id": "", "title": "Deadliest Catch"}, {"id": "", "title": "Gold Rush"}]},
    "Globoplay": {"url": "https://globoplay.globo.com", "category": "Filmes", "icon": "\U0001F3AC", "color": "#E41E2C",
                  "deep_link": "", "url_template": "https://globoplay.globo.com/{id}",
                  "top_content": [{"id": "", "title": "Big Brother Brasil"}, {"id": "", "title": "Cidade Invisivel"}, {"id": "", "title": "Todas as Mulheres"}]},
    "Vix": {"url": "https://www.vix.com", "category": "Filmes", "icon": "\U0001F3AC", "color": "#E30613",
            "deep_link": "", "url_template": "https://www.vix.com/{id}",
            "top_content": [{"id": "", "title": "La Reina del Sur"}, {"id": "", "title": "El Señor de los Cielos"}, {"id": "", "title": "Secretos de Familia"}]},
    "Curiosity Stream": {"url": "https://curiositystream.com", "category": "Filmes", "icon": "\U0001F52D", "color": "#1A1A2E",
                         "deep_link": "", "url_template": "https://curiositystream.com/{id}",
                         "top_content": [{"id": "", "title": "Deep Planet"}, {"id": "", "title": "Ancient Earth"}, {"id": "", "title": "Breakthrough"}]},
    "MUBI": {"url": "https://mubi.com", "category": "Filmes", "icon": "\U0001F3AC", "color": "#000000",
             "deep_link": "", "url_template": "https://mubi.com/films/{id}",
             "top_content": [{"id": "", "title": "Film of the Day"}, {"id": "", "title": "Cult Classics"}, {"id": "", "title": "New Releases"}]},
    "Shudder": {"url": "https://www.shudder.com", "category": "Filmes", "icon": "\U0001F47B", "color": "#FF3333",
                "deep_link": "", "url_template": "https://www.shudder.com/{id}",
                "top_content": [{"id": "", "title": "The Last Drive-In"}, {"id": "", "title": "Creepshow"}, {"id": "", "title": "Late Night with the Devil"}]},
    "BritBox": {"url": "https://www.britbox.com", "category": "Filmes", "icon": "\U0001F1EC\U0001F1E7", "color": "#2C3E50",
                "deep_link": "", "url_template": "https://www.britbox.com/{id}",
                "top_content": [{"id": "", "title": "Doctor Who"}, {"id": "", "title": "Broadchurch"}, {"id": "", "title": "Downton Abbey"}]},
    "Tubi": {"url": "https://tubitv.com", "category": "Filmes", "icon": "\U0001F4FA", "color": "#FA382F",
             "deep_link": "", "url_template": "https://tubitv.com/{id}",
             "top_content": [{"id": "", "title": "Free Movies"}, {"id": "", "title": "TV Shows"}, {"id": "", "title": "Anime"}]},
    "Plex": {"url": "https://www.plex.tv", "category": "Filmes", "icon": "\U0001F3AC", "color": "#EBAF00",
             "deep_link": "", "url_template": "https://app.plex.tv/{id}",
             "top_content": [{"id": "", "title": "Live TV"}, {"id": "", "title": "Free Movies"}, {"id": "", "title": "My Library"}]},
    "Kodi": {"url": "https://kodi.tv", "category": "Videos", "icon": "\U0001F3AC", "color": "#17B2E7",
             "deep_link": "", "url_template": "https://kodi.tv/{id}",
             "top_content": [{"id": "", "title": "Add-ons"}, {"id": "", "title": "Movies"}, {"id": "", "title": "TV Shows"}]},
    "Jellyfin": {"url": "https://jellyfin.org", "category": "Videos", "icon": "\U0001F3AC", "color": "#9B59B6",
                 "deep_link": "", "url_template": "https://jellyfin.org/{id}",
                 "top_content": [{"id": "", "title": "Movies"}, {"id": "", "title": "TV Shows"}, {"id": "", "title": "Music"}]},
    "Mixer": {"url": "https://mixer.com", "category": "Videos", "icon": "\U0001F6A8", "color": "#0024AF",
              "deep_link": "", "url_template": "https://mixer.com/{id}",
              "top_content": [{"id": "", "title": "Trending"}, {"id": "", "title": "Gaming"}, {"id": "", "title": "Creative"}]},
    "Vimeo": {"url": "https://vimeo.com", "category": "Videos", "icon": "\U0001F3AC", "color": "#1AB7EA",
              "deep_link": "", "url_template": "https://vimeo.com/{id}",
              "top_content": [{"id": "", "title": "Staff Picks"}, {"id": "", "title": "Best of the Year"}, {"id": "", "title": "Categories"}]},
    "Rumble": {"url": "https://rumble.com", "category": "Videos", "icon": "\U0001F4FA", "color": "#85C7DE",
               "deep_link": "", "url_template": "https://rumble.com/{id}",
               "top_content": [{"id": "", "title": "Trending"}, {"id": "", "title": "News"}, {"id": "", "title": "Sports"}]},
    "Tidal": {"url": "https://tidal.com", "category": "Musica", "icon": "\U0001F3B5", "color": "#000000",
              "deep_link": "", "url_template": "https://tidal.com/{id}",
              "top_content": [{"id": "", "title": "Tidal Rising"}, {"id": "", "title": "HiFi Playlists"}, {"id": "", "title": "New Releases"}]},
    "Deezer": {"url": "https://www.deezer.com", "category": "Musica", "icon": "\U0001F3B5", "color": "#A238FF",
               "deep_link": "", "url_template": "https://deezer.com/{id}",
               "top_content": [{"id": "", "title": "Editorial"}, {"id": "", "title": "Podcasts"}, {"id": "", "title": "New Releases"}]},
    "Mixcloud": {"url": "https://www.mixcloud.com", "category": "Musica", "icon": "\U0001F3B5", "color": "#5000E5",
                 "deep_link": "", "url_template": "https://mixcloud.com/{id}",
                 "top_content": [{"id": "", "title": "Trending"}, {"id": "", "title": "Fresh Mixes"}, {"id": "", "title": "Live Sets"}]},
}
